# Generated by Django 4.2.6 on 2023-11-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lec5', '0002_product_date_added_product_description_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
