# Generated by Django 4.2.6 on 2023-11-03 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw5', '0009_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
