# Generated by Django 4.2.6 on 2023-11-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw5', '0011_category_product_description_product_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
