# Generated by Django 4.2.6 on 2023-10-26 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='summ',
            new_name='order_summ',
        ),
    ]
